<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.tcfbank.com" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="SecretCodeAuthentication" targetNamespace="http://www.tcfbank.com">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="SecretCodeAuthenticationBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  <wsdl:types>
    <xsd:schema xmlns:mrm="http://www.tcfbank.com" targetNamespace="http://www.tcfbank.com" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:include schemaLocation="tcfbank.mxsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="SecretCodeAuthentication_in">
    <wsdl:part element="tns:SecretCodeAuthenticationRequest" name="SecretCodeAuthenticationRequest"/>
  </wsdl:message>
  <wsdl:message name="SecretCodeAuthentication_out">
    <wsdl:part element="tns:SecretCodeAuthenticationResponse" name="SecretCodeAuthenticationResponse"/>
  </wsdl:message>
  <wsdl:portType name="SecretCodeAuthenticationPortType">
    <wsdl:operation name="SecretCodeAuthentication">
      <wsdl:input message="tns:SecretCodeAuthentication_in" name="SecretCodeAuthentication_Input"/>
      <wsdl:output message="tns:SecretCodeAuthentication_out" name="SecretCodeAuthentication_Output"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SecretCodeAuthenticationBinding" type="tns:SecretCodeAuthenticationPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="SecretCodeAuthentication">
      <soap:operation/>
      <wsdl:input name="SecretCodeAuthentication_Input">
        <soap:body parts="SecretCodeAuthenticationRequest" use="literal"/>
      </wsdl:input>
      <wsdl:output name="SecretCodeAuthentication_Output">
        <soap:body parts="SecretCodeAuthenticationResponse" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SecretCodeAuthenticationService">
    <wsdl:port binding="tns:SecretCodeAuthenticationBinding" name="SecretCodeAuthenticationProvider">
      <soap:address location="http://hera.tcfbank.com:7800/mb/ws/SecretCodeAuthentication"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
