<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.tcfbank.com" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="StatementOrder" targetNamespace="http://www.tcfbank.com">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="StatementOrderBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  <wsdl:types>
    <xsd:schema xmlns:mrm="http://www.tcfbank.com" targetNamespace="http://www.tcfbank.com" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:include schemaLocation="tcfbank.mxsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="StatementOrder_in">
    <wsdl:part element="tns:StatementOrderRequest" name="StatementOrderRequest"/>
  </wsdl:message>
  <wsdl:message name="StatementOrder_out">
    <wsdl:part element="tns:StatementOrderResponse" name="StatementOrderResponse"/>
  </wsdl:message>
  <wsdl:portType name="StatementOrderPortType">
    <wsdl:operation name="StatementOrder">
      <wsdl:input message="tns:StatementOrder_in" name="StatementOrder_Input"/>
      <wsdl:output message="tns:StatementOrder_out" name="StatementOrder_Output"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="StatementOrderBinding" type="tns:StatementOrderPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="StatementOrder">
      <soap:operation/>
      <wsdl:input name="StatementOrder_Input">
        <soap:body parts="StatementOrderRequest" use="literal"/>
      </wsdl:input>
      <wsdl:output name="StatementOrder_Output">
        <soap:body parts="StatementOrderResponse" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="StatementOrderService">
    <wsdl:port binding="tns:StatementOrderBinding" name="StatementOrderProvider">
      <soap:address location="https://hera.tcfbank.com:7900/mb/claws/StatementOrder"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
